FROM osrf/ros:noetic-desktop-full

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Minimal setup
RUN apt-get update && apt-get install -y \
    git-all \
    python3-vcstool \
    python3-rosdep \
    wget \
    sudo

# Catkin tools
RUN sudo sh \
    -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" \
        > /etc/apt/sources.list.d/ros-latest.list'
RUN wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
RUN sudo apt-get update && sudo apt-get install python3-catkin-tools curl -y

# OpenMORE
WORKDIR openmore_ws 
RUN mkdir src

# Initialize Catkin workspace
RUN catkin init 
RUN catkin config --install
RUN catkin config --extend /opt/ros/$ROS_DISTRO

# Clone dependencies using vcs
RUN cd src
RUN git clone --recurse-submodules https://github.com/JRL-CARI-CNR-UNIBS/OpenMORE.git -b devel
RUN curl -o /openmore_ws/src/deps.repos https://raw.githubusercontent.com/JRL-CARI-CNR-UNIBS/OpenMORE/devel/deps.repos
RUN vcs import src < /openmore_ws/src/deps.repos --recursive

# Install dependencies with rosdep
RUN cd ..
RUN rosdep install --from-paths src --ignore-src -r -y

# Install additional ROS dependencies
RUN sudo apt install ros-$ROS_DISTRO-trac-ik-kinematics-plugin -y
RUN sudo apt install ros-$ROS_DISTRO-chomp-motion-planner -y
RUN sudo apt install ros-$ROS_DISTRO-moveit-planners-chomp -y
RUN sudo apt install ros-$ROS_DISTRO-pilz-industrial-motion-planner -y

# Build workspace
RUN source /opt/ros/$ROS_DISTRO/setup.bash && catkin build -cs --verbose

CMD source ~/source_env_variables && /bin/bash
