FROM osrf/ros:noetic-desktop-full

SHELL [ "/bin/bash" , "-c" ]

RUN apt-get update && apt-get install -y \
    git-all \
    python3-vcstool \
    python3-rosdep \
    wget \
    curl \
    python3-catkin-tools 

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list && \
    wget http://packages.ros.org/ros.key -O - | apt-key add - && \
    apt-get update

WORKDIR /root/openmore_ws
RUN mkdir -p src && catkin init && \
    catkin config --install && \
    catkin config --extend /opt/ros/$ROS_DISTRO

WORKDIR /root/openmore_ws/src
RUN git clone --recurse-submodules https://github.com/JRL-CARI-CNR-UNIBS/OpenMORE.git -b devel
WORKDIR /root/openmore_ws
RUN vcs import src < src/OpenMORE/deps.repos --recursive

RUN rosdep update && \
    rosdep install --from-paths src --ignore-src -r -y

RUN apt-get install -y \
    ros-$ROS_DISTRO-trac-ik-kinematics-plugin \
    ros-$ROS_DISTRO-chomp-motion-planner \
    ros-$ROS_DISTRO-moveit-planners-chomp \
    ros-$ROS_DISTRO-pilz-industrial-motion-planner \
    && rm -rf /var/lib/apt/lists/*

RUN source /opt/ros/$ROS_DISTRO/setup.bash && catkin build --verbose

CMD ["/bin/bash"]
